app:
  name: "dingding"
  mode: "dev"
  port: 8886
  version: "v0.0.1"
  start_time: "2020-07-01"
  machine_id: 1

mysql:
  host: "110.40.228.197"
  port: "3306"
  user: "root"
  password: "3yueruanjian!"
  dbname: "ding_v3_marchsoft"
  max_open_conns: 200
  max_idle_conns: 50
redis:
  db: 4
  addr: 121.43.119.224:6379
  password: "18737480171..Yy"

log:
  level: "info"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7
auth:
  jwt_expire: 8760
kafka:
  address: "121.43.119.224:9092"
classCourse:
  host: 110.40.228.197
  port: 8886
miniProgram:
  appkey: dingepndjqy7etanalhi
  appsecret: rlmRqtlLfm7tTAM8fTim3WNSwyWbd-KM3wTZ8wBtwKX8Pw6M4ZzEiIQVrCqKgCwu



